curl -o RoyalRecruits.png
curl -o Lightning.png
curl -o ThreeMusketeers.png
curl -o Miner.png
curl -o Princess.png
curl -o GoblinBarrel.png
curl -o BabyDragon.png
curl -o Minions.png
curl -o Golem.png
curl -o Rascals.png
curl -o SkeletonBarrel.png
curl -o FireSpirits.png
curl -o WallBreakers.png
curl -o Fisherman.png
curl -o Wizard.png
curl -o Clone.png
curl -o MiniP.E.K.K.A.png
curl -o Poison.png
curl -o GoblinCage.png
curl -o EliteBarbarians.png
curl -o Cannon.png
curl -o GoblinHut.png
curl -o RoyalGiant.png
curl -o Rage.png
curl -o BattleRam.png
curl -o GoblinGang.png
curl -o Bats.png
curl -o Executioner.png
curl -o Freeze.png
curl -o BombTower.png
curl -o DarkPrince.png
curl -o Valkyrie.png
curl -o MegaMinion.png
curl -o RoyalHogs.png
curl -o BarbarianBarrel.png
curl -o MinionHorde.png
curl -o Rocket.png
curl -o SkeletonArmy.png
curl -o Balloon.png
curl -o Earthquake.png
curl -o SpearGoblins.png
curl -o DartGoblin.png
curl -o MegaKnight.png
curl -o Witch.png
curl -o Arrows.png
curl -o LavaHound.png
curl -o BattleHealer.png
curl -o Zap.png
curl -o Mirror.png
curl -o ElectroWizard.png
curl -o Tombstone.png
curl -o InfernoTower.png
curl -o ElixirCollector.png
curl -o Bomber.png
curl -o NightWitch.png
curl -o Musketeer.png
curl -o Furnace.png
curl -o FlyingMachine.png
curl -o Hunter.png
curl -o Lumberjack.png
curl -o CannonCart.png
curl -o ElectroDragon.png
curl -o Barbarians.png
curl -o GiantSkeleton.png
curl -o RamRider.png
curl -o ElixirGolem.png
curl -o IceWizard.png
curl -o Guards.png
curl -o HogRider.png
curl -o Bowler.png
curl -o Heal.png
curl -o GiantSnowball.png
curl -o RoyalGhost.png
curl -o Tornado.png
curl -o Bandit.png
curl -o Mortar.png
curl -o Prince.png
curl -o BarbarianHut.png
curl -o Knight.png
curl -o Goblins.png
curl -o Zappies.png
curl -o InfernoDragon.png
curl -o Sparky.png
curl -o GoblinGiant.png
curl -o Graveyard.png
curl -o P.E.K.K.A.png
curl -o Giant.png
curl -o MagicArcher.png
curl -o IceGolem.png
curl -o IceSpirit.png
curl -o Tesla.png
curl -o Fireball.png
curl -o Archers.png
curl -o Skeletons.png
curl -o X-Bow.png
curl -o TheLog].png
curl -o .png

