curl -o RoyalRecruits
curl -o Lightning
curl -o ThreeMusketeers
curl -o Miner
curl -o Princess
curl -o GoblinBarrel
curl -o BabyDragon
curl -o Minions
curl -o Golem
curl -o Rascals
curl -o SkeletonBarrel
curl -o FireSpirits
curl -o WallBreakers
curl -o Fisherman
curl -o Wizard
curl -o Clone
curl -o MiniP.E.K.K.A
curl -o Poison
curl -o GoblinCage
curl -o EliteBarbarians
curl -o Cannon
curl -o GoblinHut
curl -o RoyalGiant
curl -o Rage
curl -o BattleRam
curl -o GoblinGang
curl -o Bats
curl -o Executioner
curl -o Freeze
curl -o BombTower
curl -o DarkPrince
curl -o Valkyrie
curl -o MegaMinion
curl -o RoyalHogs
curl -o BarbarianBarrel
curl -o MinionHorde
curl -o Rocket
curl -o SkeletonArmy
curl -o Balloon
curl -o Earthquake
curl -o SpearGoblins
curl -o DartGoblin
curl -o MegaKnight
curl -o Witch
curl -o Arrows
curl -o LavaHound
curl -o BattleHealer
curl -o Zap
curl -o Mirror
curl -o ElectroWizard
curl -o Tombstone
curl -o InfernoTower
curl -o ElixirCollector
curl -o Bomber
curl -o NightWitch
curl -o Musketeer
curl -o Furnace
curl -o FlyingMachine
curl -o Hunter
curl -o Lumberjack
curl -o CannonCart
curl -o ElectroDragon
curl -o Barbarians
curl -o GiantSkeleton
curl -o RamRider
curl -o ElixirGolem
curl -o IceWizard
curl -o Guards
curl -o HogRider
curl -o Bowler
curl -o Heal
curl -o GiantSnowball
curl -o RoyalGhost
curl -o Tornado
curl -o Bandit
curl -o Mortar
curl -o Prince
curl -o BarbarianHut
curl -o Knight
curl -o Goblins
curl -o Zappies
curl -o InfernoDragon
curl -o Sparky
curl -o GoblinGiant
curl -o Graveyard
curl -o P.E.K.K.A
curl -o Giant
curl -o MagicArcher
curl -o IceGolem
curl -o IceSpirit
curl -o Tesla
curl -o Fireball
curl -o Archers
curl -o Skeletons
curl -o X-Bow
curl -o TheLog]
curl -o 
